# Generated by Django 5.1.3 on 2024-11-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=255)),
                ('car_name', models.CharField(max_length=255)),
                ('car_brand', models.CharField(max_length=255)),
                ('car_type', models.CharField(max_length=255)),
                ('car_year', models.IntegerField()),
            ],
        ),
    ]
